<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->customFormHelper($form->get('id')) ?>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('sender_email')) ?>
            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('sender')) ?>
            </div>
        </div>

    </div>

    <div class="col-sm-6">
        <div class="the-box">
            <h4 class="small-title">Opis</h4>
            <?php echo $this->formTextarea($form->get('footer')); ?>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('newsletter'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/newsletter.js'); ?>
