<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->partial('partial/form/basic-post-data'); ?>

        </div>

    </div>

    <div class="col-sm-6">
        <div class="the-box">
            <h4 class="small-title">Pliki</h4>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('upload')); ?>
                <a href="javascript:$('#upload').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
                <div id="queue"></div>
                <div class="files"></div>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <?php echo $this->partial('partial/form/actions-post'); ?>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/post.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/datepicker.min.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap-datepicker.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/post-form.js'); ?>
