<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

<?php echo $this->customFormHelper($form->get('filename_main')); ?>
<?php echo $this->customFormHelper($form->get('filename_background')); ?>

<div class="row">
    <div class="col-sm-6">

        <div class="row">
            <div class="col-sm-12">
                <div class="the-box">
                    <h4 class="small-title">Dane podstawowe</h4>

                    <?php echo $this->partial('partial/form/basic-post-data'); ?>

                </div>
            </div>
        </div>

        <?php echo $this->languageHelper('partial/language-' . $category) ?>

    </div>

    <?php if($category == 'news'): ?>

        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <div class="the-box">
                        <h4 class="small-title">Zdjęcie główne</h4>

                        <div class="form-group">
                            <?php echo $this->customFormHelper($form->get('upload_main')); ?>
                            <a href="javascript:$('#upload-main').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                            <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
                            <div id="queue-main"></div>
                            <div class="files-main"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="the-box">
                        <h4 class="small-title">Zdjęcie w tle</h4>

                        <div class="form-group">
                            <?php echo $this->customFormHelper($form->get('upload_background')); ?>
                            <a href="javascript:$('#upload-background').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                            <div id="queue-background"></div>
                            <div class="files-background"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="the-box">
                        <h4 class="small-title">Galeria zdjęć</h4>

                        <div class="form-group">

                            <?php echo $this->customFormHelper($form->get('upload')); ?>

                            <a href="javascript:$('#upload').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                            <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>

                            <div id="queue"></div>
                            <div class="files"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    <?php endif ?>

</div>

<?php echo $this->partial('partial/meta-form', array('entity' => null)); ?>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <?php echo $this->partial('partial/form/actions-post'); ?>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/bootstrap-datetimepicker.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/post.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/post-form.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/moment.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap-datetimepicker.js'); ?>
