<?php echo $this->partial('partial/flashmessages-post'); ?>
<!-- BEGIN DATA TABLE -->
<input type="hidden" id="category" value="<?php echo $category; ?>" />
<div class="the-box">

    <table class="table table-striped table-hover" id="datatable-post" style="width: 100% !important;">
        <thead class="the-box dark full">
            <tr>
                <th class="dt-body-center"><input type="checkbox" name="check-all" class="check-all i-grey" data-toggle="tooltip" title="Podgląd" /></th>
                <th>Nazwa</th>
                <th>Url</th>
                <th>Data</th>
                <th>status_id</th>
                <th>Status</th>
                <th>Akcje</th>
            </tr>
        </thead>
    </table>

    <div class="row">
        <div class="col-sm-12">
            <a class="btn btn-facebook pull-right" href="<?php echo $this->url('post/create', array('category' => $category)); ?>">Dodaj nowy</a>
        </div>
    </div>

</div><!-- /.the-box .default -->
<div class="massive-action">
    <select name="massive-action">
        <option value="">Masowe działania</option>
        <option value="delete">Usuń wybrane</option>
        <option value="status">Zmień status</option>
    </select>
</div>
<!-- END DATA TABLE -->
<?php echo $this->partial('partial/delete-post-modal'); ?>
<?php echo $this->partial('partial/delete-massive-post-modal'); ?>
<?php echo $this->partial('partial/status-massive-post-modal'); ?>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.dataTables.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.dataTables.responsive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/bootstrap.datatable.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/post.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.responsive.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap.datatable.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/post-list.js'); ?>
