<?php
    $form = $this->form;
    $form->prepare();
?>


    <?php if($this->escapeHtml($this->messages)) : ?>
        <div class="alert alert-warning alert-bold-border fade in alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Uwaga!</strong> <?php echo $this->escapeHtml($this->messages); ?>.
        </div>
    <?php endif; ?>
    <?php echo $this->form()->openTag($form) ?>
        <div class="form-group has-feedback lg left-feedback no-label">
            <?php echo $this->formInput($form->get('email')); ?>
            <span class="fa fa-envelope form-control-feedback"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-warning btn-lg btn-perspective btn-block">ZMIEŃ HASŁO</button>
        </div>
    <?php echo $this->form()->closeTag() ?>
    <p class="text-center"><strong><a href="<?php echo $this->url('login') ?>">Powrót do logowania</a></strong></p>