    <?php
        $form = $this->form;
        $form->prepare();
    ?>

    <?php if($this->escapeHtml($this->messages)) : ?>
    <div class="alert alert-warning alert-bold-border fade in alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Uwaga!</strong> <?php echo $this->escapeHtml($this->messages); ?>.
    </div>
    <?php endif; ?>

    <?php echo $this->form()->openTag($form); ?>
        <div class="form-group has-feedback lg left-feedback no-label">
            <?php echo $this->formInput($form->get('email')); ?>
            <span class="fa fa-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback lg left-feedback no-label">
            <?php echo $this->formInput($form->get('password')); ?>
            <span class="fa fa-unlock-alt form-control-feedback"></span>
        </div>
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <?php echo $this->formInput($form->get('rememberme')); ?> Zapamiętaj mnie
                </label>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formInput($form->get('submit')); ?>
        </div>
    <?php echo $this->form()->closeTag(); ?>
<!--    <p class="text-center"><strong><a href="--><?php //echo $this->url('forgotten-password') ?><!--">Zapomniałeś hasła</a></strong></p>-->
<!--    <p class="text-center">lub</p>-->
<!--    <p class="text-center"><strong><a href="--><?php //echo $this->url('registration') ?><!--">Utwórz konto</a></strong></p>-->