<?php $metaForm = $this->metaHelper()->getMetaForm($this->entity); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <h4 class="small-title">Tagi meta <i class="fa fa-question-circle" data-toggle="popover" title="Wykorzystanie meta tagów w wyszukiwarkach:" data-content="<img src='<?php echo $this->basePath(); ?>/img/meta.png' />"></i></h4>
            <div class="form-group">
                <div class="form-group has-feedback">
                    <?php echo $this->formLabel($metaForm->get('title')); ?>
                    <?php echo $this->formInput($metaForm->get('title')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="form-group has-feedback">
                    <?php echo $this->formLabel($metaForm->get('keywords')); ?>
                    <?php echo $this->formInput($metaForm->get('keywords')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="form-group has-feedback">
                    <?php echo $this->formLabel($metaForm->get('description')); ?>
                    <?php echo $this->formTextarea($metaForm->get('description')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/meta.css'); ?>

<script>
    $(function () {
        $('[data-toggle="popover"]').popover({
            html: true
        })
    })
</script>