<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formInput($form->get('id')); ?>
<div class="row">
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Dane podstawowe</h4>
            <div class="form-group">

                <?php echo $this->customFormHelper($form->get('name')->setAttributes(array('disabled' => 'disabled'))); ?>

            </div>
            <div class="form-group">

                <?php echo $this->customFormHelper($form->get('latitude')->setAttributes(array('disabled' => 'disabled'))); ?>

            </div>
            <div class="form-group">

                <?php echo $this->customFormHelper($form->get('longitude')->setAttributes(array('disabled' => 'disabled'))); ?>

            </div>
            <?php echo $this->formInput($form->get('country')); ?>
            <?php echo $this->formInput($form->get('region')); ?>
            <?php echo $this->formInput($form->get('city')); ?>
            <?php echo $this->formInput($form->get('street')); ?>
            <?php echo $this->formInput($form->get('street_number')); ?>
        </div>

    </div>

    <div class="col-sm-6">

        <div class="row">
            <div class="col-sm-12">
                <div class="the-box">
                    <h4 class="small-title">Punkt na mapie</h4>

                    <div style="width: 100%; height: 500px;" id="map"></div>
                </div>
            </div>
        </div>

    </div>

</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-primary" href="<?php echo $this->url('place'); ?>">Powrót</a> &nbsp
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/formgps.css'); ?>
<?php $this->headScript()->appendFile("http://maps.google.com/maps/api/js?v=3.exp&libraries=places&sensor=false"); ?>
<script src="<?php echo $this->basePath().'/js/formgps-preview.js'; ?>"></script>
