<div class="row">
    <div class="col-sm-12">
        <div class="panel with-nav-tabs panel-default">
            <div class="panel-heading">
                <ul class="nav nav-tabs">

                    <?php /* @var $lang \CmsIr\System\Model\Language */ ?>
                    <?php foreach($languages as $lang): ?>

                        <li role="presentation" class="<?php echo $lang->getUrlShortcut() == 'pl' ? 'active' : '' ?>"><a aria-controls="<?php echo $lang->getUrlShortcut() ?>" role="tab" data-toggle="tab" href="#<?php echo $lang->getUrlShortcut() ?>"><?php echo $lang->getName() ?></a></li>

                    <?php endforeach ?>

                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">

                    <?php foreach($languages as $lang): ?>

                        <div role="tabpanel" class="tab-pane fade in <?php echo $lang->getUrlShortcut() == 'pl' ? 'active' : '' ?>" id="<?php echo $lang->getUrlShortcut() ?>">

                            <div class="form-group  has-feedback">
                                <label> Tytuł </label>
                                <input name="<?php echo $lang->getUrlShortcut() ?>-title" id="title" type="text" placeholder="Wprowadź tytuł" value="<?php echo isset($values[$lang->getUrlShortcut(). '-title']) ? $values[$lang->getUrlShortcut(). '-title'] : '' ?>" class="form-control">
                            </div>

                            <div class="form-group  has-feedback">
                                <label> Podtytuł </label>
                                <input name="<?php echo $lang->getUrlShortcut() ?>-subtitle" id="subtitle" type="text" placeholder="Wprowadź podtytuł" value="<?php echo isset($values[$lang->getUrlShortcut(). '-subtitle']) ? $values[$lang->getUrlShortcut(). '-subtitle'] : '' ?>" class="form-control">
                            </div>

                            <div class="form-group  has-feedback">
                                <label> Przycisk </label>
                                <input name="<?php echo $lang->getUrlShortcut() ?>-button" id="button" type="text" placeholder="Wprowadź zawartość przycisku" value="<?php echo isset($values[$lang->getUrlShortcut(). '-button']) ? $values[$lang->getUrlShortcut(). '-button'] : '' ?>" class="form-control">
                            </div>

                        </div>

                    <?php endforeach ?>

                </div>
            </div><!-- /.panel-body -->
        </div>
    </div>
</div>