<!-- BEGIN DATA TABLE -->
<div class="the-box">

    <table class="table table-striped table-hover" id="datatable-log-event" style="width: 100% !important;">
        <thead class="the-box dark full">
        <tr>
            <th class="dt-body-center"><input type="checkbox" name="check-all" class="check-all i-grey" data-toggle="tooltip" title="Podgląd" /></th>
            <th>Moduł</th>
            <th>Użytkownik</th>
            <th>Działanie</th>
            <th>Akcja</th>
            <th>Tytuł</th>
            <th>Data</th>
            <th>Status</th>
        </tr>
        </thead>
    </table>

    <div class="row">
        <div class="col-sm-12">
        </div>
    </div>

</div><!-- /.the-box .default -->
<div class="massive-action">
    <select name="massive-action">
        <option value="">Masowe działania</option>
        <option value="status">Zmień status</option>
    </select>
</div>
<!-- END DATA TABLE -->
<?php echo $this->partial('partial/status-massive-log-event-modal'); ?>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.dataTables.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.dataTables.responsive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/bootstrap.datatable.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/log-event.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.responsive.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap.datatable.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/log-event-list.js'); ?>
