<?php echo $this->partial('partial/flashmessages-system'); ?>

<div class="alert alert-success alert-bold-border square fade in alert-dismissable" id="test-mail-alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    Pomyślnie wysłano testowego e-maila.
</div>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->formInput($form->get('id')); ?>
<div class="row">
    <div class="col-sm-6">
        <div class="the-box">

            <h4 class="small-title">Dane podstawowe</h4>

            <?php echo $this->customFormHelper($form->get('host')); ?>
            <?php echo $this->customFormHelper($form->get('username')); ?>
            <?php echo $this->customFormHelper($form->get('password')); ?>

        </div>
    </div>

    <div class="col-sm-6">
        <div class="the-box">

            <?php echo $this->customFormHelper($form->get('send')); ?>

            <div class="row">
                <div class="col-sm-12">
                    <button class="btn btn-info pull-right" id="send-test-email">Wyślij testowego maila</button>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('mail-config'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/mail.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/mail.js'); ?>