<div class="row">
    <div class="col-sm-12">
        <input type="hidden" id="treeId" value="<?php echo $treeId; ?>"/>
        <div class="the-box">
            <h4 class="small-title"><?php echo $menuTree->getName(); ?></h4>
            <div class="input-group col-sm-12">
            <?php if(!empty($menu)) : ?>
                <div class="dd" id="nestable3">
                    <ol class="dd-list">

                        <?php foreach($menu as $item): ?>
                        <li class="dd-item dd3-item" data-id="<?php echo $item->getId(); ?>">

                            <?php if(is_array($item->getItems())) : ?>
                                <?php
                                    $subItems = $item->getItems();
                                    $settings = $item->getSettings();
                                    $fistItem = end($subItems);
                                    $label = $fistItem->getLabel();
                                    $url = $fistItem->getUrl();
                                    $subtitle = $fistItem->getSubtitle();

                                    array_pop($subItems);
                                ?>
                                <div class="dd-handle dd3-handle">Drag</div>
                                <div class="dd3-content">
                                    <span class="label"><?php echo $label; ?></span> <span class="url"><?php echo $url; ?></span> <span class="subtitle"><?php echo $subtitle; ?></span>
                                    <div class="pull-right">
                                        <?php if(!is_null($settings)): ?>
                                            <a href="<?php echo $this->url('page/edit', array('page_id' => $settings)); ?>" class="btn btn-facebook" data-toggle="tooltip" title="Edycja strony"><i class="fa fa-file-text-o"></i></a>
                                        <?php endif; ?>
                                        <a href="#" class="btn btn-primary" data-toggle="tooltip" title="Edycja" id="<?php echo $item->getProviderType(); ?>"><i class="fa fa-pencil"></i></a>
                                        <a href="#" class="btn btn-danger" data-toggle="tooltip" title="Usuwanie"><i class="fa fa-trash-o"></i></a>
                                    </div>
                                </div>
                                    <ol class="dd-list">
                                        <?php foreach($subItems as $subItem): ?>
                                            <?php
                                                $subItemNode = $subItem->getItems();
                                                $settings = $subItem->getSettings();

                                                $label = $subItemNode->getLabel();
                                                $url = $subItemNode->getUrl();
                                                $id = $subItemNode->getId();
                                                $subtitle = $subItemNode->getSubtitle();
                                            ?>
                                            <li class="dd-item dd3-item" data-id="<?php echo $id; ?>">
                                                <div class="dd-handle dd3-handle">Drag</div>
                                                <div class="dd3-content">
                                                    <span class="label"><?php echo $label; ?></span> <span class="url"><?php echo $url; ?></span> <span class="subtitle"><?php echo $subtitle; ?></span>
                                                    <div class="pull-right">
                                                        <?php if(!is_null($settings)): ?>
                                                            <a href="<?php echo $this->url('page/edit', array('page_id' => $settings)); ?>" class="btn btn-facebook" data-toggle="tooltip" title="Edycja strony"><i class="fa fa-file-text-o"></i></a>
                                                        <?php endif; ?>
                                                        <a href="#" class="btn btn-primary"  data-toggle="tooltip" title="Edycja" id="<?php echo $subItem->getProviderType(); ?>"><i class="fa fa-pencil"></i></a>
                                                        <a href="#" class="btn btn-danger" data-toggle="tooltip" title="Usuwanie"><i class="fa fa-trash-o"></i></a>
                                                    </div>
                                                </div>
                                            </li>
                                        <?php endforeach; ?>
                                    </ol>

                            <?php else : ?>
                                <?php
                                    $subItem = $item->getItems();
                                    $settings = $item->getSettings();

                                    $label = $subItem->getLabel();
                                    $url = $subItem->getUrl();
                                    $id = $subItem->getId();
                                    $subtitle = $subItem->getSubtitle();
                                ?>
                                <div class="dd-handle dd3-handle">Drag</div>
                                <div class="dd3-content">
                                    <span class="label"><?php echo $label; ?></span> <span class="url"><?php echo $url; ?></span> <span class="subtitle"><?php echo $subtitle; ?></span>
                                    <div class="pull-right">
                                        <?php if(!is_null($settings)): ?>
                                            <a href="<?php echo $this->url('page/edit', array('page_id' => $settings)); ?>" class="btn btn-facebook" data-toggle="tooltip" title="Edycja strony"><i class="fa fa-file-text-o"></i></a>
                                        <?php endif; ?>
                                        <a href="#" class="btn btn-primary"  data-toggle="tooltip" title="Edycja" id="<?php echo $item->getProviderType(); ?>"><i class="fa fa-pencil"></i></a>
                                        <a href="#" class="btn btn-danger"  data-toggle="tooltip" title="Usuwanie"><i class="fa fa-trash-o"></i></a>
                                    </div>
                                </div>
                            <?php endif; ?>

                        </li>
                        <?php endforeach; ?>

                    </ol>
                </div>
            <?php endif; ?>

            <a class="btn btn-facebook pull-right" href="#">Dodaj nowy</a>

            <div class="col-sm-1  pull-right">
                <select name="page-type" id="page-type" class="form-control">
                    <option value="page">Strona</option>
                    <option value="page-provider">Url</option>
                </select>
            </div>

            <a class="btn btn-default pull-right" href="<?php echo $this->url('menu'); ?>">Anuluj</a>

            </div>

        </div>
    </div>
</div>
<?php echo $this->partial('partial/create-page-node-modal'); ?>
<?php echo $this->partial('partial/create-node-modal'); ?>
<?php echo $this->partial('partial/delete-node-modal'); ?>
<?php echo $this->partial('partial/edit-node-modal'); ?>
<?php echo $this->partial('partial/edit-page-node-modal'); ?>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/menu.css'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.nestable.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/menu-edit-node.js'); ?>
