<?php if(!empty($parts)) : ?>

    <div class="nestable3 dd">
        <ol class="dd-list">

            <?php /* @var $part \CmsIr\Page\Model\PagePart */ ?>
            <?php foreach($parts as $part): ?>
                <li class="dd-item dd3-item" data-id="<?php echo $part->getId(); ?>">

                    <div class="dd-handle dd3-handle">Drag</div>
                    <div class="dd3-content">
                        <span class="label"><?php echo $part->getName(); ?></span>
                    </div>

                </li>
            <?php endforeach; ?>

        </ol>
    </div>

<?php endif; ?>