
<?php echo $this->partial('partial/flashmessages'); ?>
<!-- BEGIN DATA TABLE -->
<div class="the-box">
    <div class="table-responsive">
        <table class="table table-striped table-hover" id="datatable-subscriber-group">
            <thead class="the-box dark full">
            <tr>
                <th>Nazwa</th>
                <th>Nazwa systemowa</th>
                <th>Akcje</th>

            </tr>
            </thead>
        </table>

        <div class="row">
            <div class="col-sm-12">
                <a class="btn btn-facebook pull-right" href="<?php echo $this->url('newsletter/subscriber-group/create'); ?>">Dodaj nowy</a>
            </div>
        </div>

    </div><!-- /.table-responsive -->
</div><!-- /.the-box .default -->
<!-- END DATA TABLE -->
<?php echo $this->partial('partial/delete-group-modal'); ?>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.dataTables.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/bootstrap.datatable.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/newsletter.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap.datatable.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/subscriber.js'); ?>
