<!-- Modal -->
<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Dodawanie opcji</h4>
            </div>
            <form action="" method="post">

                <div class="modal-body">
                    <div class="form-group">
                        <label for="label">Nazwa:</label>
                        <input class="form-control" type="text" id="label"/>
                    </div>
                    <div class="form-group">
                        <div class="form group has-feedback">
                            <label for="url">Url:</label>
                            <input class="form-control" type="text" id="url"/>
                            <span class="glyphicon glyphicon-remove form-control-feedback" style="display:none;"></span>
                        </div>
                        <small data-bv-validator="notEmpty" class="help-block" style="display:none; color: #E9573F">Taki url już istnieje!</small>
                        <div class="form-group">
                            <label for="upload">Ikona:</label><br/>
                            <input type="hidden" id="filename" name="filename" class="filename" />
                            <input type="file" id="upload" class="upload" />
                            <div id="queue"></div>
                            <div class="files"></div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <img src="<?php echo $this->basePath() ?>/img/ajax-loader.gif" alt="spinner" class="pull-left spinner" />
                    <input type="submit" name="del" value="Anuluj" class="btn btn-default" data-dismiss="modal"/>
                    <input type="submit" name="save" value="Zapisz" class="btn btn-primary" />
                </div><!-- /.modal-footer -->

            </form>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-doalog -->
</div><!-- /#deleteModal -->