<!-- Modal -->
<div class="modal fade" id="createPagePartModal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Dodawanie opcji</h4>
            </div>
            <form action="" method="post">

                <div class="modal-body">
                    <div class="form-group">
                        <div class="form group has-feedback">
                            <label for="page">Strona:</label>
                            <?php if(!empty($existingPages)): ?>
                            <select name="page-part" id="page-part" class="form-control">
                                <?php /* @var $page \CmsIr\Page\Model\PagePart */ ?>
                                <?php foreach($pageParts as $page): ?>


                                    <option value="/strona-rozbudowana/<?php echo $page->getName() ?>"><?php echo $page->getName() ?></option>
                                <?php endforeach; ?>
                            </select>
                            <?php else: ?>
                                <br/> Brak aktywnych stron dostępnych w aplikacji.
                            <?php endif; ?>
                            <span class="glyphicon glyphicon-remove form-control-feedback" style="display:none;"></span>
                        </div>
                        <small data-bv-validator="notEmpty" class="help-block" style="display:none; color: #E9573F">Taki url już istnieje!</small>

                    </div>

                </div>
                <div class="modal-footer">
                    <img src="<?php echo $this->basePath() ?>/img/ajax-loader.gif" alt="spinner" class="pull-left spinner" />
                    <input type="submit" name="del" value="Anuluj" class="btn btn-default" data-dismiss="modal"/>
                    <input type="submit" name="save" value="Zapisz" class="btn btn-primary" />
                </div><!-- /.modal-footer -->

            </form>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-doalog -->
</div><!-- /#deleteModal -->