<!-- Modal -->
<div class="modal fade" id="createPageModal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Dodawanie opcji</h4>
            </div>
            <form action="" method="post">

                <div class="modal-body">
                    <div class="form-group">
                        <div class="form group has-feedback">
                            <label for="page">Strona:</label>
                            <?php if(!empty($existingPages)): ?>
                            <select name="page" id="page" class="form-control">

                                <?php foreach($existingPages as $page): ?>
                                    <?php
                                        $pageName = $page['name'];
                                        $pageSlug = $page['slug'];
                                    ?>
                                    <option value="/strona/<?php echo $pageSlug; ?>"><?php echo $pageName; ?></option>
                                <?php endforeach; ?>
                            </select>
                            <?php else: ?>
                                <br/> Brak aktywnych stron dostępnych w aplikacji.
                            <?php endif; ?>
                            <span class="glyphicon glyphicon-remove form-control-feedback" style="display:none;"></span>
                        </div>
                        <small data-bv-validator="notEmpty" class="help-block" style="display:none; color: #E9573F">Taki url już istnieje!</small>
                        <div class="form-group">
                            <label for="upload">Ikona:</label><br/>
                            <input type="hidden" id="filename" name="filename" class="filename" />
                            <input type="file" id="upload" class="upload" />
                            <div id="queue"></div>
                            <div class="files"></div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <img src="<?php echo $this->basePath() ?>/img/ajax-loader.gif" alt="spinner" class="pull-left spinner" />
                    <input type="submit" name="del" value="Anuluj" class="btn btn-default" data-dismiss="modal"/>
                    <input type="submit" name="save" value="Zapisz" class="btn btn-primary" />
                </div><!-- /.modal-footer -->

            </form>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-doalog -->
</div><!-- /#deleteModal -->