<div class="form-group">
    <label><?php echo $this->formLabel($form->get('name')); ?></label>
    <?php echo $this->formInput($form->get('name')); ?>
    <?php echo $this->formElementErrors()
        ->setMessageOpenFormat('<small data-bv-validator="notEmpty" class="help-block" style="color: #E9573F">')
        ->setMessageCloseString('</small>')
        ->render($form->get('name'))
    ?>
</div>

