<?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<input type="hidden" id="category" value="<?php echo $category; ?>" />
<?php echo $this->customFormHelper($form->get('filename')); ?>

<div class="row">
    <div class="col-sm-6">
        <div class="the-box">

            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->customFormHelper($form->get('name')) ?>

            <div class="form-group">
                <label><?php echo $this->formLabel($form->get('category_id')); ?></label>
                <?php echo $this->formSelect($form->get('category_id')); ?>
            </div>

        </div>
    </div>
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Pliki</h4>

            <?php echo $this->customFormHelper($form->get('upload')); ?>
            <a href="javascript:$('#upload').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
            <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
            <div id="queue"></div>
            <div class="files"></div>

        </div>

    </div>
</div>

<?php echo $this->languageHelper('partial/language-dictionary', $blocks) ?>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('dictionary', array('category' => $category)); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/dictionary.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/dictionary-form.js'); ?>