<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Dane podstawowe</h4>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('password_last')); ?>

                <?php if(isset($message)): ?>

                    <small data-bv-validator="notEmpty" class="help-block" style="color: #E9573F"><?php echo $message ?></small>

                    <script>
                        $('.form-group').addClass('has-error has-feedback');
                    </script>

                <?php endif ?>

            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('password_new')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('password_confirm')); ?>
            </div>

        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('users-list'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>

<?php
echo $this->form()->closeTag($form);
?>