<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->formInput($form->get('filename')); ?>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('name')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('surname')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('email')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <div class="form-group">
                <label><?php echo $this->formLabel($form->get('role')); ?></label>
                <?php echo $this->formSelect($form->get('role')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('position')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('facebook')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('twitter')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('google')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>
        </div>

    </div>

    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Pliki</h4>
            <div class="form-group">
                <div class="files"></div>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-primary" href="<?php echo $this->url('users-list'); ?>">Powrót</a> &nbsp
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/users.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/users-form.js'); ?>
