<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->formInput($form->get('filename')); ?>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('name')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('surname')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>
            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('email')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <div class="form-group">
                <label><?php echo $this->formLabel($form->get('role')); ?></label>
                <?php echo $this->formSelect($form->get('role')->setAttributes(array('disabled' => 'disabled'))); ?>
            </div>

            <?php if(isset($extraFields)): ?>

                <?php foreach($extraFields as $field): ?>
                    <div class="form-group">
                        <div class="form-group has-feedback">
                            <?php
                            $type = $field['type'];
                            $attributes = $field['attributes'];
                            $options = $field['options'];
                            ?>
                            <label><?php echo $options['label']; ?></label>
                            <?php
                            $attributesString = preg_replace('/^(.*)$/e', ' "$1=\'". $attributes["$1"]."\'" ',array_flip($attributes));
                            $attributesString = implode(' ' , $attributesString);
                            switch($type)
                            {
                                case 'text':
                                    echo '<input type="text" '.$attributesString.' value="'.$options['value'].'" disabled="disabled" />';
                                    break;
                                case 'select':
                                    echo '<select '.$attributesString.' disabled="disabled">';
                                    foreach($options['value'] as $key => $value)
                                    {
                                        echo '<option value="'.$key.'">'.$value.'</option>';
                                    }
                                    echo '</select>';
                                    break;
                                case 'textarea':
                                    echo '<textarea '.$attributesString.' disabled="disabled">'.$options['value'].'</textarea>';
                                    break;
                            }
                            ?>
                        </div>
                    </div>
                <?php endforeach; ?>

            <?php endif; ?>
        </div>

    </div>

    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Pliki</h4>
            <div class="form-group">
                <div class="files"></div>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-primary" href="<?php echo $this->url('users'); ?>">Powrót</a> &nbsp
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/users.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/users-form.js'); ?>
