<?php echo $this->formInput($form->get('id')); ?>
<?php echo $this->formInput($form->get('filename')); ?>

<div class="form-group">

    <?php echo $this->customFormHelper($form->get('name')); ?>

</div>
<div class="form-group">

    <?php echo $this->customFormHelper($form->get('url')); ?>

</div>
<div class="form-group">

    <?php echo $this->customFormHelper($form->get('status_id')); ?>

</div>

<?php if($category == 'events'): ?>

    <div class="form-group">
        <div class="form-group has-feedback">
            <label>Data od:</label>
            <?php echo $this->formInput($form->get('date_from')->setAttribute('class', 'form-control datetimepicker')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="form-group has-feedback">
            <label>Data do:</label>
            <?php echo $this->formInput($form->get('date_to')->setAttribute('class', 'form-control datetimepicker')); ?>
        </div>
    </div>

<?php else: ?>

    <div class="form-group">
        <div class="form-group has-feedback">
            <label>Data:</label>
            <?php echo $this->formInput($form->get('date_from')->setAttribute('class', 'form-control datetimepicker')); ?>
        </div>
    </div>

<?php endif; ?>

<div class="form-group">

    <?php echo $this->customFormHelper($form->get('author_id')); ?>

</div>

<div class="form-group">
    <label><?php echo $this->formLabel($form->get('text')); ?></label>

    <?php echo $this->formTextarea($form->get('text')); ?>
</div>