<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Cms-ir') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/style-responsive.css')
        ->prependStylesheet($this->basePath() . '/plugins/icheck/skins/all.css');
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/apps.js')
        ->prependFile($this->basePath() . '/plugins/icheck/icheck.min.js')
        ->prependFile($this->basePath() . '/plugins/backstretch/jquery.backstretch.min.js')
        ->prependFile($this->basePath() . '/plugins/slimscroll/jquery.slimscroll.min.js')
        ->prependFile($this->basePath() . '/plugins/nicescroll/jquery.nicescroll.min.js')
        ->prependFile($this->basePath() . '/plugins/retina/retina.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js');
    ?>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login tooltips bg-dark">
    <div class="login-header text-center">
        <img src="<?php echo $this->basePath() ?>/img/logo-login.png" class="logo" alt="Logo">
    </div>
    <div class="login-wrapper">
        <?php echo $this->content; ?>
    </div>

</body>
</html>