<!-- BEGIN TOP NAV -->
<div class="top-navbar">
<div class="top-navbar-inner">

    <!-- Begin Logo brand -->
    <div class="logo-brand">
<!--        <a href="--><?php //echo $this->url('home'); ?><!--"><img src="/img/logo-login.png" alt="Sentir logo"></a>-->
    </div><!-- /.logo-brand -->
    <!-- End Logo brand -->

    <div class="top-nav-content no-right-sidebar">

        <!-- Begin button sidebar left toggle -->
        <div class="btn-collapse-sidebar-left">
            <i class="fa fa-bars"></i>
        </div><!-- /.btn-collapse-sidebar-left -->
        <!-- End button sidebar left toggle -->

        <!-- Begin button nav toggle -->
        <div class="btn-collapse-nav" data-toggle="collapse" data-target="#main-fixed-nav">
            <i class="fa fa-plus icon-plus"></i>
        </div><!-- /.btn-collapse-sidebar-right -->
        <!-- End button nav toggle -->


        <!-- Begin user session nav -->
        <ul class="nav-user navbar-right">
            <li class="dropdown">
                <a href="#fakelink" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="/img/avatar.jpg" class="avatar img-circle" alt="Avatar">
                    <?php
                        $name = $this->loggedUser->name;
                        $surname = $this->loggedUser->surname;
                    ?>
                    <strong><?php echo $name . ' ' . $surname ?></strong>
                </a>
                <ul class="dropdown-menu square primary margin-list-rounded with-triangle">
<!--                    <li><a href="#fakelink">Account setting</a></li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li><a href="lock-screen.html">Lock screen</a></li>-->
                    <li><a href="<?php echo $this->url('users/change-password'); ?>">Zmień hasło</a></li>
                    <li><a href="<?php echo $this->url('logout'); ?>">Wyloguj się</a></li>
                </ul>
            </li>
        </ul>
        <!-- End user session nav -->

        <!-- Begin Collapse menu nav -->
        <div class="collapse navbar-collapse" id="main-fixed-nav">
            <!-- Begin nav search form -->
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
            </form>
            <!-- End nav search form -->
            <ul class="nav navbar-nav navbar-left">
                <!-- Begin nav notification -->
                <li class="dropdown">
                    <a href="#fakelink" class="dropdown-toggle" data-toggle="dropdown">
                        <?php if($unreadEvents > 0): ?>
                            <span class="badge badge-danger icon-count"><?php echo $unreadEvents; ?></span>
                        <?php endif; ?>
                        <i class="fa fa-bell"></i>
                    </a>
                    <ul class="dropdown-menu square with-triangle">
                        <li>
                            <div class="nav-dropdown-heading">
                                Ostatnie działania
                            </div><!-- /.nav-dropdown-heading -->
                            <div class="nav-dropdown-content scroll-nav-dropdown">
                                <ul>
                                    <?php foreach($latestEvents as $event): ?>
                                        <?php
                                            $cssClass = strtolower($event->getAction());
                                            if($event->getViewed() == 0)
                                            {
                                                $cssClass .= ' unread';
                                            }

                                            $file = '/img/avatar.jpg';
                                            if($event->getFilename())
                                            {
                                                $file = '/files/users/'.$event->getFilename();
                                            }
                                        ?>
                                        <li class="<?php echo $cssClass; ?>">
                                            <a href="#">
                                                <img src="<?php echo $file; ?>" class="absolute-left-content img-circle" alt="Avatar">
                                                <strong><?php echo $event->getUser(); ?></strong> <?php echo $event->getWhat(); ?>
                                                <span class="small-caps">"<?php echo $event->getDescription(); ?>"</span>
                                                <span class="small-caps"><?php echo $event->getDate(); ?></span>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div><!-- /.nav-dropdown-content scroll-nav-dropdown -->
                            <button class="btn btn-primary btn-square btn-block" onclick="window.location.href='<?php echo $this->url('log-event'); ?>'">Zobacz wszystkie działania</button>
                        </li>
                    </ul>
                </li>
                <!-- End nav notification -->
            </ul>
        </div><!-- /.navbar-collapse -->
    <!-- End Collapse menu nav -->
    </div><!-- /.top-nav-content -->

</div><!-- /.top-navbar-inner -->
</div><!-- /.top-navbar -->
<!-- END TOP NAV -->