<!-- BEGIN SIDEBAR LEFT -->
<div class="sidebar-left sidebar-nicescroller">
    <?php
        $layoutViewModel = $this->viewModel()->getRoot();
        $userRole = $layoutViewModel->loggedUser->role;
        $currentWebsiteId = $_COOKIE['website_id'];
    ?>

    <!-- Some HTML -->
    <ul class="sidebar-menu">
        <?php foreach ($this->container as $page): ?>
            <?php if($userRole >= $page->getId()): ?>
                <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                <?php $hasChildren = $page->hasPages() ?>
                <?php if( ! $hasChildren): ?>
                    <?php if(!$page->website_id || $page->website_id == $currentWebsiteId): ?>
                        <li <?php if($page->isActive()) echo 'class="selected"'?> id="<?php echo $page->getId(); ?>">
                            <a class="nav-header" href="<?php echo $page->getHref() ?>">
                                <i class="<?php echo $page->getClass(); ?> icon-sidebar"></i>
                                <?php echo $this->translate($page->getLabel()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php else: ?>

                    <?php $flag = 0; ?>

                    <?php foreach($page->getPages() as $child): ?>
                        <?php if($child->isActive()) $flag = 1; ?>
                    <?php endforeach; ?>

                    <?php if($flag == 1): ?>
                        <?php if(!$page->website_id || $page->website_id == $currentWebsiteId): ?>
                        <li class="active" id="<?php echo $page->getId(); ?>">

                            <a href="#">
                                <i class="<?php echo $page->getClass(); ?> icon-sidebar"></i>
                                <i class="fa fa-angle-right chevron-icon-sidebar"></i>
                                <span><?php echo $this->translate($page->getLabel()) ?></span>
                            </a>

                            <ul class="submenu" style="display: block;">
                                <?php foreach($page->getPages() as $realActiveChild): ?>
                                    <?php if($userRole >= $realActiveChild->getId()): ?>
                                        <?php if(!$realActiveChild->website_id || $realActiveChild->website_id == $currentWebsiteId): ?>
                                        <?php if($realActiveChild->visibleInPrimary == true): ?>
                                        <li <?php if($realActiveChild->isActive()) echo 'class="selected"'?>>
                                            <a href="<?php echo $realActiveChild->getHref() ?>">
                                                 <?php echo $this->translate($realActiveChild->getLabel()) ?>
                                            </a>
                                        </li>
                                        <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                 <?php endforeach; ?>
                            </ul>
                        </li>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if(!$page->website_id || $page->website_id == $currentWebsiteId): ?>
                        <li>

                            <a href="#">
                                <i class="<?php echo $page->getClass(); ?> icon-sidebar"></i>
                                <i class="fa fa-angle-right chevron-icon-sidebar"></i>
                                <span><?php echo $this->translate($page->getLabel()) ?></span>
                            </a>

                            <ul class="submenu">
                                <?php foreach($page->getPages() as $realChild): ?>
                                    <?php if($userRole >= $realChild->getId()): ?>
                                        <?php if( ! $realChild->isVisible() || !$this->navigation()->accept($realChild)) continue; ?>
                                        <?php if(!$realChild->website_id || $realChild->website_id == $currentWebsiteId): ?>
                                        <?php if($realChild->visibleInPrimary == true): ?>
                                        <li <?php if($realChild->isActive()) echo 'class="selected"'?>>

                                            <a href="<?php echo $realChild->getHref() ?>">

                                                <?php echo $this->translate($realChild->getLabel()) ?>

                                            </a>

                                        </li>
                                        <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endif ?>
            <?php endif; ?>
        <?php endforeach ?>
    </ul>
</div><!-- /.sidebar-left -->