<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php $container = $this->navigation()->breadcrumbs()  ?>

<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>
<?php $navigation = $container->getContainer() ?>

<ol class="breadcrumb default square rsaquo sm">
    <?php $active = $container->findActive($navigation) ?>
    <li>
        <a href="<?php echo $this->url('dashboard') ?>"><i class="fa fa-home"></i></a>
    </li>
    <?php $i = 0; ?>
    <?php foreach($this->pages as $page): ?>

            <?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
            <?php if(!$page->isActive()): ?>
                <li>
                    <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a>
                </li>
            <?php else: ?>
                <?php if($page->getLabel() != 'Dashboard'): ?>
                    <li class="active">
                        <?php if($container->getLinkLast()): ?>
                            <a href="<?php echo $page->getHref() ?>">
                        <?php endif ?>
                            <?php echo $page->getLabel() ?>
                        <?php if($container->getLinkLast()): ?>
                            </a>
                        <?php endif ?>
                    </li>
                <?php endif ?>
            <?php endif ?>

        <?php $i++; ?>

    <?php endforeach ?>
</ol>