<!-- BEGIN TOP NAV -->
<div class="top-navbar">
<div class="top-navbar-inner">

    <!-- Begin Logo brand -->
    <div class="logo-brand">
<!--        <a href="--><?php //echo $this->url('home'); ?><!--"><img src="/img/logo-login.png" alt="Sentir logo"></a>-->
        <a href="<?php echo $this->url('home') ?>"><img class="logo" id="logo"
                                                                             src="/images-front/logo-lombard.svg" width="120px"
                                                                             alt="Lombard"></a>
    </div><!-- /.logo-brand -->
    <!-- End Logo brand -->

    <div class="top-nav-content no-right-sidebar">

        <!-- Begin button sidebar left toggle -->
        <div class="btn-collapse-sidebar-left">
            <i class="fa fa-bars"></i>
        </div><!-- /.btn-collapse-sidebar-left -->
        <!-- End button sidebar left toggle -->

        <!-- Begin button nav toggle -->
        <div class="btn-collapse-nav" data-toggle="collapse" data-target="#main-fixed-nav">
            <i class="fa fa-plus icon-plus"></i>
        </div><!-- /.btn-collapse-sidebar-right -->
        <!-- End button nav toggle -->


        <!-- Begin user session nav -->
        <ul class="nav-user navbar-right">
            <li class="dropdown">
                <a href="#fakelink" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="/img/avatar.jpg" class="avatar img-circle" alt="Avatar">
                    <?php
                        $name = $this->loggedUser->name;
                        $surname = $this->loggedUser->surname;
                    ?>
                    <strong><?php echo $name . ' ' . $surname ?></strong>
                </a>
                <ul class="dropdown-menu square primary margin-list-rounded with-triangle">
<!--                    <li><a href="#fakelink">Account setting</a></li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li><a href="lock-screen.html">Lock screen</a></li>-->
                    <li><a href="<?php echo $this->url('users/change-password'); ?>">Zmień hasło</a></li>
                    <li><a href="<?php echo $this->url('logout'); ?>">Wyloguj się</a></li>
                </ul>
            </li>
        </ul>
        <!-- End user session nav -->

        <!-- Begin Collapse menu nav -->
        <div class="collapse navbar-collapse" id="main-fixed-nav">
            <!-- Begin nav search form -->

        </div><!-- /.navbar-collapse -->
    <!-- End Collapse menu nav -->
    </div><!-- /.top-nav-content -->

</div><!-- /.top-navbar-inner -->
</div><!-- /.top-navbar -->
<!-- END TOP NAV -->