<!-- BEGIN SIDEBAR LEFT -->
<div class="sidebar-left sidebar-nicescroller">
    <ul class="sidebar-menu">

        <li class="selected">
            <a href="<?php echo $this->url('dashboard'); ?>">
                <i class="fa fa-dashboard icon-sidebar"></i>
                Dashboard
            </a>
        </li>

    </ul>

    <?php echo $this->navigation('Navigation')->menu(); ?>
</div><!-- /.sidebar-left -->
<!-- END SIDEBAR LEFT -->