<?php
$this->headScript()->appendFile("http://maps.google.com/maps/api/js?v=3.exp&libraries=places&sensor=false");
?>
<?php $form->prepare() ?>

<?php echo $this->form()->openTag($form) ?>

<?php $placeFieldset = $form->get('place') ?>
<?php $this->bootstrapFormRow()->setTranslatorTextDomain('sys-ui') ?>

<?php echo $this->bootstrapFormRow($placeFieldset->get('name')) ?>

<?php
    /* @var $element Zend\Form\Element\Text  */
    $element = $placeFieldset->get('location');
    $element->setLabelAttributes(array('class' => 'control-label col-sm-2 text-right'));
    $element->setAttribute('class', 'form-control gps-field-btn');

    $errors = (string) $this->formElementErrors($element);
    $hasErrors = !empty($errors);
?>

<div class="form-group clearfix place-location <?php echo ($hasErrors) ? 'has-error' : ''?>">
    <?php echo $this->formLabel($element) ?>
    <div class="col-sm-10">
        <div class="input-group location-input-group">
            <?php echo $this->formElement($element) ?>
            <span class="input-group-btn">
                <button class="btn btn-default open-map" type="button"><?php echo $this->translate('Point on the map', 'sys-ui') ?></button>
            </span>
        </div>
        <span class="help-block"><?= $this->translate('Geographical coordinates in format: (latitude, longitude)', 'sys-ui') ?></span>
        <span class="help-block"><?php echo $errors ?></span>
    </div>
</div>

<?php echo $this->bootstrapFormRow($placeFieldset->get('country')) ?>
<?php echo $this->bootstrapFormRow($placeFieldset->get('region_id')) ?>
<?php echo $this->bootstrapFormRow($placeFieldset->get('city')) ?>

<div class="form-actions-with-border">
    <?php echo $this->bootstrapFormRow($form->get('save')) ?>
    <?php echo $this->bootstrapFormRow($form->get('back')) ?>
</div>

<?php echo $this->form()->closeTag() ?>

<?php $this->asset()->append('sys-gps') ?>
<?php echo $this->partial('partials/place-map-modal.phtml'); ?>

