<?php

if (empty($entity))
{
    throw new \Exception('You have to pass entity form to news-delete-modal partial!');
}

?>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->translate('Deleting place', 'sys-ui') ?></h3>
</div>

<div class="modal-body form-modal-body">

    <form method="post" action="" class="form-entity-delete">

        <fieldset>
            <p><?php echo $this->translate('cms.place.deletion.confirmation', 'sys-messages') ?></p>
            <input type="hidden" name="entity_id" value="<?php echo $entity->getId() ?>">
        </fieldset>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary"><?php echo $this->translate('Delete place', 'sys-ui') ?></button>
            <button class="btn" data-dismiss="modal"><?php echo $this->translate('Cancel', 'sys-ui') ?></button>
        </div>

    </form>

</div>