<div id="gpsmodal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gpsmodal-label" aria-hidden="true">
    <div style="width: 60%;" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="gpsmodal-label"><?php echo $this->translate('Select_location from the map', 'sys-ui') ?></h3>
            </div>
            <div class="modal-body">
                <div class="col-sm-12 searchMap"><input type="text" id="search" placeholder="<?php echo $this->translate('Search city', 'sys-ui') ?>" class="form-control"/></div>

                <div style="width: 100%; height: 600px;" class="map"></div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close', 'sys-ui') ?></button>
            </div>
        </div>
    </div>
</div>