<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

<?php echo $this->customFormHelper($form->get('filename_main')); ?>
<?php echo $this->customFormHelper($form->get('filename')); ?>

    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <div class="the-box">

                        <h4 class="small-title">Dane podstawowe</h4>

                        <?php echo $this->customFormHelper($form->get('name')) ?>

                    </div>
                </div>
            </div>

            <?php echo $this->languageHelper('partial/language-page-part', $blocks) ?>

        </div>
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <div class="the-box">
                        <h4 class="small-title">Zdjęcie główne</h4>

                        <div class="form-group">
                            <?php echo $this->customFormHelper($form->get('upload_main')); ?>
                            <a href="javascript:$('#upload-main').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                            <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
                            <div id="queue-main"></div>
                            <div class="files-main"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="the-box">
                        <h4 class="small-title">Galeria zdjęć</h4>

                        <div class="form-group">

                            <?php echo $this->customFormHelper($form->get('upload')); ?>

                            <a href="javascript:$('#upload').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                            <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>

                            <div id="queue"></div>
                            <div class="files">
                                <?php if(!empty($pageFiles)): ?>
                                    <?php /* @var $file \CmsIr\File\Model\File */ ?>
                                    <?php foreach($pageFiles as $file): ?>
                                        <div id="<?php echo $file->getId() ?>" class="deletePhoto">
                                            <i class="fa fa-times" data-toggle="tooltip" title="Usuń zdjęcie"></i>
                                            <img src="/files/page-part/<?php echo $file->getFilename() ?>" alt="<?php echo $file->getFilename() ?>" class="thumb" />
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="the-box">
                <div class="input-group col-sm-12 text-right">
                    <a class="btn btn-default" href="<?php echo $this->url('page/part' ,array('page_id' => $pageId)); ?>">Anuluj</a> &nbsp
                    <?php echo $this->formInput($form->get('submit')); ?>
                </div>
            </div>
        </div>
    </div>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/page.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/page-part-form.js'); ?>