<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<?php echo $this->customFormHelper($form->get('id')) ?>
<?php echo $this->customFormHelper($form->get('filename')); ?>

<div class="row">
    <div class="col-sm-6">
        <div class="the-box">

            <h4 class="small-title">Dane podstawowe</h4>
            <div class="form-group">
                <label><?php echo $this->formLabel($form->get('status_id')); ?></label>
                <?php echo $this->formSelect($form->get('status_id')); ?>
            </div>

            <?php echo $this->customFormHelper($form->get('name')) ?>

            <?php echo $this->customFormHelper($form->get('title')) ?>

            <?php echo $this->customFormHelper($form->get('description')) ?>

            <?php echo $this->customFormHelper($form->get('url')) ?>

        </div>
    </div>
    <div class="col-sm-6">

        <div class="the-box">
            <h4 class="small-title">Pliki</h4>

            <?php echo $this->customFormHelper($form->get('upload')); ?>
            <a href="javascript:$('#upload').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
            <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
            <div id="queue"></div>
            <div class="files"></div>

        </div>

    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('slider'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>

<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/slider-item-form.js'); ?>