<?php echo $this->customFormHelper($form->get('id')) ?>
<div class="form-group">
    <?php echo $this->customFormHelper($form->get('email')) ?>
</div>
<div class="form-group">
    <?php echo $this->customFormHelper($form->get('first_name')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('confirmation_code')); ?></label>
    <?php echo $this->formInput($form->get('confirmation_code')->setAttributes(array('disabled' => 'disabled'))) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('groups')); ?></label>
    <?php echo $this->formSelect($form->get('groups')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('status_id')); ?></label>
    <?php echo $this->formSelect($form->get('status_id')) ?>
</div>

