<?php echo $this->customFormHelper($form->get('id')) ?>
<div class="form-group">
    <?php echo $this->customFormHelper($form->get('subject')) ?>
</div>
<div class="form-group">
    <label><?php echo $this->formLabel($form->get('status_id')); ?></label>
    <?php echo $this->formSelect($form->get('status_id')) ?>
</div>

<div class="form-group">
    <label><?php echo $this->formLabel($form->get('groups')); ?></label>
    <?php echo $this->formSelect($form->get('groups')) ?>
</div>