<div class="row">
    <div class="col-sm-12">
        <div class="panel with-nav-tabs panel-default">
            <div class="panel-heading">
                <ul class="nav nav-tabs">

                    <?php /* @var $lang \CmsIr\System\Model\Language */ ?>
                    <?php foreach($languages as $lang): ?>

                        <li role="presentation" class="<?php echo $lang->getUrlShortcut() == 'pl' ? 'active' : '' ?>"><a aria-controls="<?php echo $lang->getUrlShortcut() ?>" role="tab" data-toggle="tab" href="#<?php echo $lang->getUrlShortcut() ?>"><?php echo $lang->getName() ?></a></li>

                    <?php endforeach ?>

                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">

                    <?php foreach($languages as $lang): ?>

                        <div role="tabpanel" class="tab-pane fade in <?php echo $lang->getUrlShortcut() == 'pl' ? 'active' : '' ?>" id="<?php echo $lang->getUrlShortcut() ?>">

                            <div class="form-group  has-feedback">
                                <label> Klient </label>
                                <input name="<?php echo $lang->getUrlShortcut() ?>-client" id="client" type="text" placeholder="Wprowadź imię i nazwisko klienta" value="<?php echo isset($values[$lang->getUrlShortcut(). '-client']) ? $values[$lang->getUrlShortcut(). '-client'] : '' ?>" class="form-control">
                            </div>

                            <div class="form-group  has-feedback">
                                <label> Opinia </label>
                                <textarea name="<?php echo $lang->getUrlShortcut() ?>-content" id="content" placeholder="Wprowadź treść opinii" class="summernote-lg"><?php echo isset($values[$lang->getUrlShortcut(). '-content']) ? $values[$lang->getUrlShortcut(). '-content'] : '' ?></textarea>
                            </div>

                        </div>

                    <?php endforeach ?>

                </div>
            </div><!-- /.panel-body -->
        </div>
    </div>
</div>


