<div class="the-box">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-1"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Odwiedzający w czasie rzeczywistym</h3>
                </div>
                <div id="panel-collapse-1" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="445" src="<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Live&actionToWidgetize=widget&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div><!-- /.panel-body -->
                </div><!-- /.collapse in -->
            </div><!-- /.panel panel-default -->
        </div><!-- /.col-sm-6 -->

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-2"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Mapa odwiedzin</h3>
                </div>
                <div id="panel-collapse-2" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="445" src="<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserCountryMap&actionToWidgetize=visitorMap&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div><!-- /.panel-body -->
                </div><!-- /.collapse in -->
            </div><!-- /.panel panel-default -->
        </div><!-- /.col-sm-6 -->

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-3"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Wykres z ostatnich odwiedzin</h3>
                </div>
                <div id="panel-collapse-3" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="253" src="<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&columns[]=nb_visits&widget=1&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div><!-- /.panel-body -->
                </div><!-- /.collapse in -->
            </div><!-- /.panel panel-default -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-4"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Słowa kluczowe wyszukiwarki</h3>
                </div>
                <div id="panel-collapse-4" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="112" src=<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Actions&actionToWidgetize=getSiteSearchKeywords&idSite=1&period=day&date=yesterday&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div>
                </div>
            </div>
        </div><!-- /.col-sm-6 -->
    </div>

    <div class="row">


        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-5"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Przeglądarki odwiedzających</h3>
                </div>
                <div id="panel-collapse-5" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="280" src="<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=DevicesDetection&actionToWidgetize=getBrowsers&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div><!-- /.panel-body -->
                </div><!-- /.collapse in -->
            </div><!-- /.panel panel-default -->
        </div><!-- /.col-sm-6 -->

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-6"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Odwiedziny według czasu serwera</h3>
                </div>
                <div id="panel-collapse-6" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="280" src="<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=VisitTime&actionToWidgetize=getVisitInformationPerServerTime&idSite=1&period=day&date=yesterday&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div><!-- /.panel-body -->
                </div><!-- /.collapse in -->
            </div><!-- /.panel panel-default -->
        </div><!-- /.col-sm-6 -->

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="right-content">
                        <button class="btn btn-default btn-sm btn-rounded-lg to-collapse" data-toggle="collapse" data-target="#panel-collapse-7"><i class="fa fa-chevron-up"></i></button>
                    </div>
                    <h3 class="panel-title">Liczba obecnie aktywnych użytkowników</h3>
                </div>
                <div id="panel-collapse-7" class="collapse in">
                    <div class="panel-body">
                        <iframe width="100%" height="280" src="<?php echo $piwik; ?>/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Live&actionToWidgetize=getSimpleLastVisitCount&idSite=1&period=day&date=yesterday&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                    </div><!-- /.panel-body -->
                </div><!-- /.collapse in -->
            </div><!-- /.panel panel-default -->
        </div><!-- /.col-sm-6 -->

    </div>
</div>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/dashboard.css'); ?>